<?php

namespace ContainerTN60UyJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LO4x_WCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lO4x.wC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lO4x.wC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'fileUploaderService' => ['privates', 'App\\Services\\FileUploaderService', 'getFileUploaderServiceService', true],
        ], [
            'fileUploaderService' => 'App\\Services\\FileUploaderService',
        ]);
    }
}
