<?php

namespace ContainerCxzrof6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFileUploaderServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\FileUploaderService' shared autowired service.
     *
     * @return \App\Services\FileUploaderService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'FileUploaderService.php';

        return $container->privates['App\\Services\\FileUploaderService'] = new \App\Services\FileUploaderService($container);
    }
}
