<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTN60UyJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTN60UyJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTN60UyJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTN60UyJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTN60UyJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'TN60UyJ',
    'container.build_id' => '2dcf5cad',
    'container.build_time' => 1612523818,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTN60UyJ');
